# roles/websites/vars/main.yml
websites:
    ollama:
        domains: ['ollama.kaxtus.com']
        port: 11434
        ssl_enabled: true
        ssl_email: "info@kaxtus.com"
        template: 'proxy_app'
    kaxtus:
        domains: ['kaxtus.com', 'www.kaxtus.com']
        repo_url: 'git@github.com:kaxtus/homePage.git'
        docker_image_name: 'kaxtus-website'
        root_name: 'kaxtus-website'
        bin_dir: 'dist'
        ssl_enabled: true
        ssl_email: "admin@kaxtus.com"
        template: 'static_site'
    gaspi:
        domains: ['gaspi.aero', 'www.gaspi.aero', 'www.gaspico.com', 'gaspico.com']
        repo_url: 'git@github.com:OverDriveGain/gaspi.git'
        docker_image_name: 'gaspi-website'
        root_name: 'gaspi-website'
        port: 10081
        app_js_dir: 'formserver'
        ssl_enabled: true
        ssl_email: "admin@gaspi.aero"
        template: 'node_app'
    calgaryexpedite:
        domains: ['calgaryexpedite.com', 'www.calgaryexpedite.com']
        repo_url: 'git@github.com:OverDriveGain/calgaryexpedite.git'
        docker_image_name: 'calgaryexpedite-website'
        root_name: 'calgaryexpedite-website'
        port: 10084
        app_js_dir: 'formserver'
        ssl_enabled: true
        ssl_email: "admin@calgaryexpedite.com"
        template: 'node_app'
    zohreh:
        domains: ['honarmand.de', 'www.honarmand.de']
        repo_url: 'git@github.com:OverDriveGain/zohreh.git'
        docker_image_name: 'zohreh-website'
        root_name: 'zohreh-website'
        bin_dir: 'dist'
        ssl_enabled: true
        ssl_email: "admin@honarmand.de"
        template: 'static_site'
    music:
        domains: ['music.kaxtus.com']
        port: 10082
        app_secret: supersecret
        container_name: musplaya
        ssl_enabled: true
        ssl_email: "admin@kaxtus.com"
        template: 'proxy_app'
    musdowlow:
        domains: ['musdowlow.kaxtus.com']
        port: 10086
        container_name: musdowlow
        ssl_enabled: true
        ssl_email: "admin@kaxtus.com"
        template: 'proxy_app'
    nextcloud:
        domains: [ 'nextcloud.kaxtus.com' ]
        port: 10087
        container_name: nextcloud
        ssl_enabled: true
        ssl_email: "admin@kaxtus.com"
        template: 'proxy_app'
    house:
        domains: ['house.zaboub.com']
        port: 8123
        ssl_enabled: true
        ssl_email: "manar@zaboub.com"
        nginx_proxy_headers:
            upgrade: "$http_upgrade"
            connection: "upgrade"
        template: 'proxy_app'
        websocket_support: true
    quotomate:
        domains: [ 'quotomate.com', 'www.quotomate.com', 'windows.quotomate.com', 'linux.quotomate.com' ]
        repo_url: 'git@github.com:OverDriveGain/quotomate-web-ssr.git'
        docker_image_name: 'quotomate-website'
        root_name: 'quotomate-website'
        port: 10083
        app_js_dir: '.output/server'
        ssl_enabled: true
        ssl_email: "admin@quotomate.com"
        unsafe_eval: true # Used for javascript client side rendered
        subdomain_static_dirs:
            'windows.quotomate.com': '/home/manar/quotomate/win32/update/storage/repository'
            'linux.quotomate.com': '/home/manar/quotomate/linux/update/storage/repository'
        template: 'node_app_with_static'
    n8n:
        domains: [ 'n8n.kaxtus.com' ]
        repo_url: 'git@github.com:OverDriveGain/ai-assistant.git'
        root_name: 'n8n'
        port: 5678
        container_name: n8n
        ssl_enabled: true
        ssl_email: "admin@kaxtus.com"
        websocket_support: true
        websocket_paths:
            - /rest/push
        debug_logging: true
        unsafe_eval: true
        template: 'proxy_app'
    reiddt:
        domains: [ 'reiddt.com', 'www.reiddt.com' ]
        repo_url: 'git@github.com:kaxtus/rieddt.git'
        ssl_enabled: true
        ssl_email: "admin@reiddt.com"
        root_name: 'reiddt-website'
        bin_dir: './'
        template: 'static_site'
    analytics:
        domains: ['analytics.kaxtus.com' ]
        repo_url: 'git@github.com:OverDriveGain/plausible.git'
        port: 5679
        ssl_enabled: true
        ssl_email: "placeholder"
        root_name: 'plausible'
        cors: true
        websocket_support: true
        template: 'proxy_app'
        unsafe_eval: true
    casabot:
        domains: ['casabot.quotomate.com']
        port: 10085
        ssl_enabled: true
        ssl_email: "info@quotomate.com"
        template: 'proxy_app'
