health_checks:
  - name: "Berlin SSH"
    category: "networking"
    type: port
    host: host.docker.internal
    check: 10022
  - name: "Laptop SSH"
    category: "networking"
    type: port
    host: host.docker.internal
    check: 10024
  - name: "Windows RDP"
    category: "networking"
    type: port
    host: host.docker.internal
    check: 3389
  - name: "Berlin RDP"
    category: "networking"
    type: port
    host: host.docker.internal
    check: 13389
