- import_tasks: install_musplaya.yml
  tags: ["music:musplaya"]

- import_tasks: install_musdowlow.yml
  tags: ["music:musdowlow"]

- import_tasks: install_promtail.yml
  tags: ["music:promtail"]

- import_tasks: install_musid.yml
  tags: ["music:musid"]

- import_tasks: install_youtube.yml
  tags: ["music:youtube"]
